### ISSUE TITLE
Usage Instructions for Windows/Linux

### ISSUE THREAD

**Issue by tarekis** [dhanishgajjar/vscode-icons#10]
I can't seem to find any usage instructions for Windows/Linux in the README, macOS only. I reasoned Windows should be supported because of  https://github.com/dhanishgajjar/vscode-icons/issues/2, but is Linux supported anyways? Am I missing something?

**Comment by dhanishgajjar** [comment]
@tarekis Done ! Added Yes Linux is supported.

**Comment by ayfati01** [comment]
The program seems to only work on windows 7. There is a way that you can change the icons on windows without a program.

1. Right click on program
2. Click "Property"
3. Select "Shortcut"
4. Select "Change Icon" button at the bottom
5. Click browse and choose the icon
6. Click "Ok"
7. Click "Apply"
8. If a permission window pops up,  click "Continue"
9. Click "Ok"
10. All done!
