### ISSUE TITLE
Windows icons are small

### ISSUE THREAD

**Issue by Tes3awy** [dhanishgajjar/vscode-icons#13]
I have changed my Code icon to stranger things. The icon is too small compared to the original one. Can you make bigger so it appear nicely?

Snapshot:

![toolbar](https://user-images.githubusercontent.com/11368432/32979657-5ef4cee8-cc62-11e7-8432-578f3af29e89.JPG)

**Comment by dhanishgajjar** [comment]
@Tes3awy is this from the most recent download? I pushed some updates. On Windows the icons look slightly smaller is because traditionally windows are in square profile, while the Mac versions are tilted. Check and let me know. Can you try a different Icon and see if that also looks small?

**Comment by Tes3awy** [comment]
@dhanishgajjar Yeah it's from the most recent update. I tried the Flash Alternative icon as well and it's small. However; I am replacing the icons using `resource hacker` and it doesn't detect a 256x256 icon size, so that's what makes the icons small as the latter dimension is the default maximum size for desktop icons on Windows.

[Check Design Concepts](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

**Comment by dhanishgajjar** [comment]
@Tes3awy These .ICO contains different resolution, however they might not contain every different resolution. I'll see what else I can do to make them perfect :) Thanks

**Comment by StevenBlasi** [comment]
I'm having the same issue with all of them.

**Comment by mohouyizme** [comment]
@dhanishgajjar Or you can make a windows version of the designs (icon on the left):

![](https://code.visualstudio.com/assets/updates/1_18/blueicon.png)

**Comment by StevenBlasi** [comment]
I didn't check but Microsoft might own that design.

**Comment by dhanishgajjar** [comment]
@Tes3awy @mohouyizme @StevenBlasi Can you guys test this version and give feedback on how it looks? Thank you.
[flash-square.ico.zip](https://github.com/dhanishgajjar/vscode-icons/files/1485385/flash-square.ico.zip)

**Comment by mohouyizme** [comment]
Cool!

**Comment by Tes3awy** [comment]
@dhanishgajjar Now it works like a charm. I want the **Stranger Things Icon**, please. Thanks for taking my issue into consideration :)

**Comment by dhanishgajjar** [comment]
@Tes3awy You will have to wait a little while, as I only test one of these icons and with my full time job it can take about a week to make all the icons in the square profile :) But I'll update and you can check when it's up. Can you share a screenshot of how it looks. I don't have access to a windows machine.

**Comment by Tes3awy** [comment]
@dhanishgajjar Sure, I'll be waiting. No problem at all in waiting. I know what a full time job means for a developer. We both know 😆 .

screenshots:

- On Desktop: 

![on-desktop](https://user-images.githubusercontent.com/11368432/32994421-ee3b1432-cd6f-11e7-932c-ef84a3445820.JPG)

- In Toolbar:

![on-toolbar](https://user-images.githubusercontent.com/11368432/32994423-fb759654-cd6f-11e7-9d38-3d317ca48fbe.JPG)

**Comment by dhanishgajjar** [comment]
@Tes3awy @mohouyizme all icons have been scaled you may check now.
