### ISSUE TITLE
Windows Icons

### ISSUE THREAD

**Issue by broodjetom** [dhanishgajjar/vscode-icons#2]
Wow! This look very cool! Too bad this is only for MacOS. Can you make some for Windows 10? Or are you already busy with it? I will leave the design to you, I'm not too good with colors!

**Comment by dhanishgajjar** [comment]
I have considered the windows version too, definitely will make those soon :)

**Comment by wesbos** [comment]
@broodjetom can you try one of the icons in this PR? https://github.com/dhanishgajjar/vscode-icons/pull/6

**Comment by stacygrace** [comment]
On Windows 10 you can use the Windows ico files to change the icon for shortcuts for the application but that doesn't appear to change how the icon appears in the start menu unfortunately. Does work for desktop shortcuts and it does alter the icon when pinned to the taskbar though.

**Comment by broodjetom** [comment]
I can try, if I would know how to 'install' it...? And like @chadmorrow said, it has to be an ico file.

**Comment by akshayvinchurkar1** [comment]
in windows i dont able to change icon of actual application instead you can change shortcut icon but the results are not good see this
![iconstate](https://user-images.githubusercontent.com/29745555/32886238-12cb2bfc-cae6-11e7-9a20-c31a3265dde3.PNG)

**Comment by dhanishgajjar** [comment]
@akshayvinchurkar1 Try the latest ones I pushed recently.

**Comment by dhanishgajjar** [comment]
@wesbos I used http://www.img2icnsapp.com to convert them manually from SVG to ICO. That way it creates the .ICO package with all different sizes. Since the automation converts from a single 256 x 256 png it has jagged edges when it scales down.

**Comment by maulikdadhaniya** [comment]
Its work perfectly in Windows @akshayvinchaukar1.
