### ISSUE TITLE
Can't have the icon viewing with VS Code

### ISSUE THREAD

**Issue by csleong98** [dhanishgajjar/vscode-icons#4]
It is now showing ICNS picture icon only even after a few restarts and restarting the Mac.

**Comment by dhanishgajjar** [comment]
@csleong98 https://cl.ly/nj6d This might help, its a simple cmd + c, right click on the application icon, select get info, select the tiny icon up top and cmd + v. Works flawlessly!

**Comment by csleong98** [comment]
Alright, ill give it try. Thx
