### ISSUE TITLE
Dragging icons worked but not copying and pasting it

### ISSUE THREAD

**Issue by csleong98** [dhanishgajjar/vscode-icons#5]
![screen shot 2017-11-15 at 11 10 21 pm](https://user-images.githubusercontent.com/6150058/32843238-3cef2b7c-ca5a-11e7-8e97-caf397d7708c.png)

**Comment by danillouz** [comment]
`cmd + V` didn't work for me either, what does work is dragging the `.icns` to the icon (in the top left) of the info pane, until you see the green plus sign and then dropping it.

**Comment by csleong98** [comment]
It seems like for my case I need to drag the icons from the folder and it worked. Conclusion dragging works but not copy and pasting.

**Comment by dhanishgajjar** [comment]
@csleong98 did dragging work for you?

**Comment by csleong98** [comment]
@dhanishgajjar yes

**Comment by tcasey** [comment]
Dragging worked for me too

**Comment by dhanishgajjar** [comment]
@tcasey Nice ! @csleong98 I'll close this now :)
