### ISSUE TITLE
Build seems to be broken

### ISSUE THREAD

**Issue by mhartington** [dhanishgajjar/vscode-icons#8]
Hi there! Im attempting to add a new icon for Oceanic-Next

![screen shot 2017-11-16 at 9 33 05 am](https://user-images.githubusercontent.com/2835826/32898609-99c36cd0-cab6-11e7-9216-a717502ffb25.png)

But the build seem to fail right away without touching anything. Is there any thing extra needed?

**Comment by dhanishgajjar** [comment]
@mhartington Hey! yeah the build has some issues, will need some refactor. Having issues with auto conversion. If you have the hex codes for colours, I'd be happy to manually create them and push it. Will link the theme repo too on the Readme?

**Comment by mhartington** [comment]
Sure thing! 

The Cyan: #5FB3B3

The Dark background : #1B2B34

The Lighter folded area, #D8DEE9 at 45% opacity

The original theme is here. https://github.com/voronianski/oceanic-next-color-scheme

**Comment by dhanishgajjar** [comment]
@mhartington Done ! you can check now :)
