### ISSUE TITLE
Can't change icon on Windows 10

### ISSUE THREAD

**Issue by packetverse** [dhanishgajjar/vscode-icons#82]
I tried changing the icon and whenever I launch vscode it changes back to it's original icon. I have also tried deleting IconCache.db, restarting the explorer.exe task and logged out and logged back in. I also tried restarting since none of those options really worked. I have also changed all of the shortcut icons so it's not only the taskbar but I also changed the shortcut icons in the start menu and then when I pin it to the taskbar it's show that icon that I want, but when I launch vscode it just reverts to original icon.

[Both images of how it changes when I launch it](https://imgur.com/a/Eg6LbWR)

**Comment by ghost** [comment]
> 

Same here.
